import Image from "next/image";
import React from "react";
import abc from "@/assets/IMG.jpg";
import little from "@/assets/littleGenie.jpg";
import hourglass from "@/assets/hourglass.png";
import Link from "next/link";

export const metadata = {
  title: "FIITJEE Bokaro || Course Details",

  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className="bg-[#F8FAFC]">
      <div className="bggg">
        <h1 className="text-5xl">Course We Offer</h1>
        <span className="font-sm text-yellow">FIITJEE BOKARO </span>
      </div>
      <div className="flex flex-col items-center justify-center ">
        <Link
          href="/course/Udaya-7"
          className="flex flex-col items-start p-[3rem]  w-[78%] sm:w-[100%]  sm:ml-0 "
        >
          {/* <div className="flex flex-col items-start p-[3rem]  w-[78%] sm:w-[100%]  sm:ml-0 "> */}
          <h1 className="text-5xl text-[#004790] sm:text-3xl font-bold">
            CLASS 7
          </h1>
          <div className="flex flex-wrap justify-evenly ">
            <div className=" mt-[2rem] cursor-pointer  hover:shadow-pink bg-primary-light  shadow-prim shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2 border-red">
                  <Image
                    src={little}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  <h1 className="text-lg font-bold">
                    Two Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This is an Ideal Program for Students who wish to climb the
                    ladder of academic success from Class VII itself.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* </div>   */}
        </Link>
        <div className="flex flex-col items-start p-[3rem]  w-[78%] sm:w-[100%]  sm:ml-0 ">
          <h1 className="text-5xl text-[#004790] sm:text-3xl font-bold">
            CLASS 8
          </h1>
          <div className="flex flex-wrap gap-20 ">
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">UDAYA</h1> */}
                  <h1 className="text-lg font-bold">
                    Two Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This is an Ideal Program for Students who wish to climb the
                    ladder of academic success from Class VIII itself.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col items-start p-[3rem]  w-[78%] sm:w-[100%] k sm:ml-0 ">
          <h1 className="text-5xl text-[#004790] sm:text-3xl font-bold">
            CLASS 9
          </h1>
          <div className="flex flex-wrap gap-40 sm:gap-10 ">
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">CLASSROOM</h1> */}
                  <h1 className="text-lg font-bold">
                    Four Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This program also prepares students comprehensively for
                    other Engineering Entrance and respective Competitive &
                    Scholastic Exams
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">ASCENT</h1> */}
                  <h1 className="text-lg font-bold">
                    Two Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This is an Ideal Program for Students who wish to climb the
                    ladder of academic success from Class VIII itself.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col items-start p-[3rem]  w-[78%] sm:w-[100%]  sm:ml-0 ">
          <h1 className="text-5xl text-[#004790] sm:text-3xl font-bold">
            CLASS 10
          </h1>
          <div className="flex flex-wrap gap-40 sm:gap-10 ">
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">CLASSROOM</h1> */}
                  <h1 className="text-lg font-bold">
                    Four Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This program also prepares students comprehensively for
                    other Engineering Entrance and respective Competitive &
                    Scholastic Exams.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">ASCENT</h1> */}
                  <h1 className="text-lg font-bold">
                    One Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This is an Ideal Program for Students who wish to climb the
                    ladder of academic success from Class VIII itself.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col items-start p-[3rem]  w-[78%] sm:w-[100%]  sm:ml-0 ">
          <h1 className="text-5xl text-[#004790] sm:text-3xl font-bold">
            CLASS 11
          </h1>
          <div className="flex flex-wrap gap-40 sm:gap-10 ">
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">CLASSROOM</h1> */}
                  <h1 className="text-lg font-bold">
                    Four Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This program also prepares students comprehensively for
                    other Engineering Entrance and respective Competitive &
                    Scholastic Exams.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">ASCENT</h1> */}
                  <h1 className="text-lg font-bold">
                    One Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This is an Ideal Program for Students who wish to climb the
                    ladder of academic success from Class VIII itself.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col items-start p-[3rem]  w-[78%] sm:w-[100%]  sm:ml-0 ">
          <h1 className="text-5xl text-[#004790] sm:text-3xl font-bold">
            CLASS 12
          </h1>
          <div className="flex flex-wrap gap-40 sm:gap-10 ">
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">CLASSROOM</h1> */}
                  <h1 className="text-lg font-bold">
                    Four Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This program also prepares students comprehensively for
                    other Engineering Entrance and respective Competitive &
                    Scholastic Exams.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">ASCENT</h1> */}
                  <h1 className="text-lg font-bold">
                    One Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This is an Ideal Program for Students who wish to climb the
                    ladder of academic success from Class VIII itself.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col items-start p-[3rem]  w-[78%] sm:w-[100%]  sm:ml-0 ">
          <h1 className="text-5xl text-[#004790] sm:text-3xl font-bold">
            CLASS 12(Passout)
          </h1>
          <div className="flex flex-wrap gap-40 sm:gap-10 ">
            <div className=" mt-[2rem] cursor-pointer hover:shadow-pink  bg-primary-light shadow-2xl w-[400px] sm:w-[100%]  rounded-xl">
              <div className="flex justify-center flex-col items-center   sm:flex-col   gap-5 p-4 sm:ml-0 rounded-sm">
                <div className="rounded-md border-2">
                  <Image
                    src={abc}
                    className="h-[20&] w-[40rem]  object-cover "
                  />{" "}
                </div>
                <div className="">
                  {/* <h1 className="text-3xl font-bold">CLASSROOM</h1> */}
                  <h1 className="text-lg font-bold">
                    Four Year Classroom Program
                  </h1>
                  <p className="   ">
                    {" "}
                    This program also prepares students comprehensively for
                    other Engineering Entrance and respective Competitive &
                    Scholastic Exams.
                  </p>
                  <div className="flex items-center gap-5 mt-2">
                    <Image
                      src={hourglass}
                      className="rounded-full h-[2rem] w-[2rem]"
                    />
                    <span className="font-bold">220 HOURS</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default page;
