import Slider from "@/components/Home/Slider";
import { slides } from "@/constants";
import WhyUS from "@/components/Home/WhyUS";
import AboutUs from "@/components/Home/AboutUs";
import Achivers from "@/components/Home/Achivers";
import Testimonials from "@/components/Testimonials";
import Contact from "@/components/Contact";
import Founder from "@/components/Founder";
import Test from "@/components/Home/Test";
export const metadata = {
  title: "FIITJEE Bokaro Center",

  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Slider slides={slides} />
      <AboutUs />
      <WhyUS />
      <Achivers />
      <Founder />
      <Testimonials />
      <Test />
      <Contact />
    </>
  );
}
