import Contact from "@/components/Contact";
import Why from "@/components/Why";
import React from "react";
export const metadata = {
  title: "Why FIITJEE?",

  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <div className="bg-[#F8FAFC]">
        <div className="bggg">
          <h1 className="text-5xl">Why FIITJEE?</h1>
          <span className="font-sm text-yellow">FIITJEE BOKARO </span>
        </div>
      </div>
      <Why />
      <Contact />
    </div>
  );
};

export default page;
